---
- name: Create Kafka Topic
  hosts: ubuntu_containers
  become: yes
  tasks:
    - name: Create topic
      command: /opt/kafka/bin/kafka-topics.sh --create --topic test-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
