version: '3'
services:
  ubuntu1:
    build: .
    container_name: ubuntu1
    ports:
      - "2222:22"

  ubuntu2:
    build: .
    container_name: ubuntu2
    ports:
      - "2223:22"

  ubuntu3:
    build: .
    container_name: ubuntu3
    ports:
      - "2224:22"
